package edu.ub.prog2.GomezFarrusVictor.vista;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mat.aules
 */
public class Demo extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        chkBotonsActius.setSelected(true);
        jTextCADET.setEnabled(true);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextCADET = new javax.swing.JTextField();
        jButtonHola = new javax.swing.JButton();
        jButtonAdeu = new javax.swing.JButton();
        chkBotonsActius = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 1, 232));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextCADET.setText("CADET");
        jTextCADET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCADETActionPerformed(evt);
            }
        });

        jButtonHola.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButtonHola.setText("HOLA");
        jButtonHola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHolaActionPerformed(evt);
            }
        });

        jButtonAdeu.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        jButtonAdeu.setText("ADEU");
        jButtonAdeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdeuActionPerformed(evt);
            }
        });

        chkBotonsActius.setText("BOTONS ACTIUS");
        chkBotonsActius.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBotonsActiusStateChanged(evt);
            }
        });
        chkBotonsActius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBotonsActiusActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextCADET, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonAdeu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButtonHola, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkBotonsActius)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdeu)
                    .addComponent(jButtonHola))
                .addGap(43, 43, 43)
                .addComponent(jTextCADET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBotonsActius))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCADETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCADETActionPerformed
        
    }//GEN-LAST:event_jTextCADETActionPerformed

    private void jButtonHolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHolaActionPerformed
        jTextCADET.setText("GG PERFECTE");
    }//GEN-LAST:event_jButtonHolaActionPerformed

    private void jButtonAdeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdeuActionPerformed
        jTextCADET.setText("GG PERFECTE X 2!");
    }//GEN-LAST:event_jButtonAdeuActionPerformed

    private void chkBotonsActiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBotonsActiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBotonsActiusActionPerformed

    private void chkBotonsActiusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBotonsActiusStateChanged
        jButtonAdeu.setEnabled(chkBotonsActius.isSelected());
        jButtonHola.setEnabled(chkBotonsActius.isSelected());
    }//GEN-LAST:event_chkBotonsActiusStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBotonsActius;
    private javax.swing.JButton jButtonAdeu;
    private javax.swing.JButton jButtonHola;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextCADET;
    // End of variables declaration//GEN-END:variables
}
