/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.GomezFarrusVictor.vista;

import edu.ub.prog2.GomezFarrusVictor.controlador.CtrlVisor;
import edu.ub.prog2.GomezFarrusVictor.model.AlbumImatges;
import edu.ub.prog2.GomezFarrusVictor.model.ExcepcioImatgeNoExisteix;
import edu.ub.prog2.GomezFarrusVictor.model.ExcepcioImatgeRepetida;
import edu.ub.prog2.GomezFarrusVictor.model.Imatge;
import edu.ub.prog2.utils.ImageFile;
import edu.ub.prog2.utils.VisorException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author mat.aules
 */
public class VisorUB4 extends javax.swing.JFrame {
    private CtrlVisor controlador;
    /**
     * Creates new form VisorUB4
     */
    public VisorUB4() {
        initComponents();
        this.controlador=new CtrlVisor();
        this.btnAfegirImatgeAlbum.setEnabled(false);
        this.btnEliminarAlbum.setEnabled(false);
        this.btnEliminarImatgeAlbum.setEnabled(false);
        this.btnEliminarImatgeBiblioteca.setEnabled(false);
        this.btnGuardarDades.setEnabled(false);
        this.btnVisualitzarAlbum.setEnabled(false);
        this.btnVisualitzarImatge.setEnabled(false);
        this.btnVisualitzarImatgeAlbum.setEnabled(false);
        this.btnVisualitzarBiblioteca.setEnabled(false);
    }
    class FrmAfegirImatge extends javax.swing.JFrame {
        private VisorUB4 visor;
        /**
         * Creates new form Demo
         */
        public FrmAfegirImatge(VisorUB4 visorUB) {
            initComponents();
            this.setVisible(true);
            this.jTextRutaImatge.setEnabled(true);
            this.visor=visorUB;
        }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jTextRutaImatge = new javax.swing.JTextField();
            btnBuscarImatge = new javax.swing.JButton();
            etUltMod = new javax.swing.JLabel();
            btnAcceptar = new javax.swing.JButton();
            btnCancelar = new javax.swing.JButton();
            etCami = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(236, 1, 232));
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            jTextRutaImatge.setText("Ruta de la imatge");
            jTextRutaImatge.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTextRutaImatgeMouseClicked(evt);
                }
            });

            btnBuscarImatge.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
            btnBuscarImatge.setText("BUSCAR");
            btnBuscarImatge.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarImatgeActionPerformed(evt);
                }
            });

            etUltMod.setText("Ultima Modificacio:");

            btnAcceptar.setText("ACCEPTAR");
            btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAcceptarActionPerformed(evt);
                }
            });

            btnCancelar.setText("CANCELAR");
            btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelarActionPerformed(evt);
                }
            });

            etCami.setText("Introduiu la ruta de la imatge:");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextRutaImatge, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addGap(4, 4, 4)
                            .addComponent(btnBuscarImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnAcceptar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar))
                        .addComponent(etCami, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etUltMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(etCami)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextRutaImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarImatge))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(etUltMod)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnAcceptar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        

        private void btnBuscarImatgeActionPerformed(java.awt.event.ActionEvent evt) {                                                
            JFileChooser seleccio = new JFileChooser();
            File fitxer;
            int resultat = seleccio.showOpenDialog(this);
            if (resultat == JFileChooser.APPROVE_OPTION) {
                fitxer=seleccio.getSelectedFile();
                this.jTextRutaImatge.setText(fitxer.toString());
                Date lastmod=new Date(fitxer.lastModified());
                this.etUltMod.setText("Ultima modificacio"+lastmod.toString());
            }
        }                                               

        private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {                                            
            try {
                this.visor.controlador.addImage(new Imatge(this.jTextRutaImatge.getText()));
                Actualitzador act=new Actualitzador(this.visor);
                act.actualitzar();
            } catch (ExcepcioImatgeRepetida ex) {
                JOptionPane.showMessageDialog(null, "Aquesta imatge ja existeix a la biblioteca");
            } catch (ExcepcioImatgeNoExisteix ex) {
                JOptionPane.showMessageDialog(null, "Aquesta imatge no existeix");
            }
            this.dispose();
        }                                           

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
            this.dispose();
        }                                           

        private void jTextRutaImatgeMouseClicked(java.awt.event.MouseEvent evt) {                                             
            this.jTextRutaImatge.setText("");
        }                                            

        // Variables declaration - do not modify                     
        private javax.swing.JButton btnAcceptar;
        private javax.swing.JButton btnBuscarImatge;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JLabel etCami;
        private javax.swing.JLabel etUltMod;
        private javax.swing.JTextField jTextRutaImatge;
        // End of variables declaration                   
    }
    class FrmCrearAlbum extends javax.swing.JFrame {
        private VisorUB4 visor;

        /**
         * Creates new form FrmCrearAlbum
         */
        public FrmCrearAlbum(VisorUB4 visorUB) {
            initComponents();
            this.setVisible(true);
            this.jTextNomAlbum.setEnabled(true);
            this.jTextX.setEnabled(true);
            this.jTextY.setEnabled(true);
            this.visor=visorUB;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jTextNomAlbum = new javax.swing.JTextField();
            btnAcceptar = new javax.swing.JButton();
            btnCancelar = new javax.swing.JButton();
            etAlbum = new javax.swing.JLabel();
            jTextX = new javax.swing.JTextField();
            jTextY = new javax.swing.JTextField();
            etGPS = new javax.swing.JLabel();
            etX = new javax.swing.JLabel();
            etY = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jTextNomAlbum.setText("Nom de l'album");
            jTextNomAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTextNomAlbumMouseClicked(evt);
                }
            });

            btnAcceptar.setText("Acceptar");
            btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAcceptarActionPerformed(evt);
                }
            });

            btnCancelar.setText("Cancelar");
            btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelarActionPerformed(evt);
                }
            });

            etAlbum.setText("Introduiu el nom de l'album:");

            jTextX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextX.setText("X");
            jTextX.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTextXMouseClicked(evt);
                }
            });

            jTextY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextY.setText("Y");
            jTextY.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTextYMouseClicked(evt);
                }
            });

            etGPS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            etGPS.setText("Posició GPS:");

            etX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            etX.setText("X");

            etY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            etY.setText("Y");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNomAlbum))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etGPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(etX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(etY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etGPS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(etX)
                                .addComponent(etY))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNomAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAcceptar)
                        .addComponent(btnCancelar)))
            );

            pack();
        }// </editor-fold>                        

        private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {                                            
            double[] posGPS=new double[2];
            posGPS[0]=Float.parseFloat(this.jTextX.getText());
            posGPS[1]=Float.parseFloat(this.jTextY.getText());
            this.visor.controlador.addAlb(this.jTextNomAlbum.getText(),posGPS );
            this.visor.combAlbums.setModel(new DefaultComboBoxModel(this.visor.controlador.getAlbsString()));
            this.visor.combAlbums.setSelectedIndex(this.visor.combAlbums.getItemCount()-1);
            Actualitzador act=new Actualitzador(this.visor);
            act.actualitzar();
            this.dispose();
        }                                           

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
            this.dispose();
        }                                           

        private void jTextXMouseClicked(java.awt.event.MouseEvent evt) {                                    
            this.jTextX.setText("");
        }                                   

        private void jTextYMouseClicked(java.awt.event.MouseEvent evt) {                                    
            this.jTextY.setText("");
        }                                   

        private void jTextNomAlbumMouseClicked(java.awt.event.MouseEvent evt) {                                           
            this.jTextNomAlbum.setText("");
        }                                          

        // Variables declaration - do not modify                     
        private javax.swing.JButton btnAcceptar;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JLabel etAlbum;
        private javax.swing.JLabel etGPS;
        private javax.swing.JLabel etX;
        private javax.swing.JLabel etY;
        private javax.swing.JTextField jTextNomAlbum;
        private javax.swing.JTextField jTextX;
        private javax.swing.JTextField jTextY;
        // End of variables declaration                   
    }
    class FrmRutaDades extends javax.swing.JFrame {
        private VisorUB4 visor;
        private boolean tipus;

        /**
         * Creates new form frmRutaDades
         */
        public FrmRutaDades(VisorUB4 visorUB,boolean type) {
            initComponents();
            this.setVisible(true);
            this.txtRuta.setEnabled(true);
            this.visor=visorUB;
            this.tipus=type;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            txtRuta = new javax.swing.JTextField();
            btnBuscar = new javax.swing.JButton();
            btnAcceptar = new javax.swing.JButton();
            btnCancelar = new javax.swing.JButton();
            etRuta = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            txtRuta.setText("Ruta");

            btnBuscar.setText("Buscar");
            btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarActionPerformed(evt);
                }
            });

            btnAcceptar.setText("Acceptar");
            btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAcceptarActionPerformed(evt);
                }
            });

            btnCancelar.setText("Cancelar");
            btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelarActionPerformed(evt);
                }
            });

            etRuta.setText("Ruta de les dades:");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etRuta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addComponent(btnAcceptar)
                        .addComponent(txtRuta))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(etRuta)
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnAcceptar)))
            );

            pack();
        }// </editor-fold>                        

        private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
            JFileChooser seleccio = new JFileChooser();
            File fitxer;
            int resultat = seleccio.showOpenDialog(this);
            if (resultat == JFileChooser.APPROVE_OPTION) {
                fitxer=seleccio.getSelectedFile();
                this.txtRuta.setText(fitxer.toString());
            }
        }                                         

        private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {                                            
            try {
                if(this.tipus){
                    this.visor.controlador.saveDades(this.txtRuta.getText());
                }else{
                    this.visor.controlador.retrDades(this.txtRuta.getText());
                }
                Actualitzador act=new Actualitzador(this.visor);
                act.actualitzar();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            } catch (FileNotFoundException ex) {
                if(this.tipus){
                    try {
                        this.visor.controlador.saveNewDades(this.txtRuta.getText());
                    } catch (IOException ex1) {
                        JOptionPane.showMessageDialog(null,ex1.getMessage());
                    }
                }else{
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            this.dispose();
        }                                           

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
            this.dispose();        // TODO add your handling code here:
        }                                           

        // Variables declaration - do not modify                     
        private javax.swing.JButton btnAcceptar;
        private javax.swing.JButton btnBuscar;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JLabel etRuta;
        private javax.swing.JTextField txtRuta;
        // End of variables declaration   
    }
    class Actualitzador{
        private VisorUB4 visor;
        public Actualitzador(VisorUB4 visorUB){
            this.visor=visorUB;
        }
        public void actualitzar(){
            if(!this.visor.controlador.getBibl().isEmpty()){
                this.visor.btnVisualitzarImatge.setEnabled(true);
                this.visor.btnEliminarImatgeBiblioteca.setEnabled(true);
                this.visor.btnVisualitzarBiblioteca.setEnabled(true);
                this.visor.btnGuardarDades.setEnabled(true);
                if(!this.visor.controlador.emptyAlbs()){
                    this.visor.btnAfegirImatgeAlbum.setEnabled(true);
                    this.visor.btnEliminarAlbum.setEnabled(true);
                    if(!this.visor.controlador.getAlb(this.visor.combAlbums.getSelectedIndex()).isEmpty()){
                        this.visor.btnEliminarImatgeAlbum.setEnabled(true);
                        this.visor.btnVisualitzarAlbum.setEnabled(true);
                        this.visor.btnVisualitzarImatgeAlbum.setEnabled(true);
                        DefaultListModel model=new DefaultListModel();
                        for(ImageFile item:this.visor.controlador.getAlb(this.visor.combAlbums.getSelectedIndex()).getArrayImgFile()){
                            Imatge img=(Imatge)item;
                            model.addElement(img.getName());
                        }
                        this.visor.listImatgesAlbum.setModel(model);
                    }else{
                        this.visor.btnEliminarImatgeAlbum.setEnabled(false);
                        this.visor.btnVisualitzarAlbum.setEnabled(false);
                        this.visor.btnVisualitzarImatgeAlbum.setEnabled(false);
                        DefaultListModel model=new DefaultListModel();
                        model.copyInto(new String[] {"Imatge1","Imatge2","Imatge3","Imatge4","Imatge5","..."});
                        this.visor.listImatgesAlbum.setModel(model);
                    }
                    this.visor.combAlbums.setModel(new DefaultComboBoxModel(this.visor.controlador.getAlbsString()));
                }else{
                    this.visor.btnAfegirImatgeAlbum.setEnabled(false);
                    this.visor.btnEliminarAlbum.setEnabled(false);
                    this.visor.btnEliminarImatgeAlbum.setEnabled(false);
                    this.visor.btnVisualitzarAlbum.setEnabled(false);
                    this.visor.btnVisualitzarImatgeAlbum.setEnabled(false);
                    DefaultListModel model=new DefaultListModel();
                    model.copyInto(new String[] {"Imatge1","Imatge2","Imatge3","Imatge4","Imatge5","..."});
                    this.visor.listImatgesAlbum.setModel(model);
                    this.visor.combAlbums.setModel(new DefaultComboBoxModel(new String[] {"Album1","Album2","Album3","Album4","Album5","..."}));
                    
                }
                DefaultListModel modelBibl = new DefaultListModel();
                modelBibl.clear();
                for(ImageFile item: this.visor.controlador.getBibl().getArrayImgFile()){
                    Imatge img=(Imatge) item;
                    modelBibl.addElement(img.getName());
                }
                modelBibl.addElement("...");
                this.visor.listImatgesBiblioteca.setModel(modelBibl);
            }else{
                this.visor.btnVisualitzarImatge.setEnabled(false);
                this.visor.btnEliminarImatgeBiblioteca.setEnabled(false);
                this.visor.btnVisualitzarBiblioteca.setEnabled(false);
                this.visor.btnGuardarDades.setEnabled(false);
                this.visor.btnAfegirImatgeAlbum.setEnabled(false);
                this.visor.btnEliminarAlbum.setEnabled(false);
                this.visor.btnEliminarImatgeAlbum.setEnabled(false);
                this.visor.btnVisualitzarAlbum.setEnabled(false);
                this.visor.btnVisualitzarImatgeAlbum.setEnabled(false);
                DefaultListModel model=new DefaultListModel();
                model.copyInto(new String[] {"Imatge1","Imatge2","Imatge3","Imatge4","Imatge5","..."});
                this.visor.listImatgesAlbum.setModel(model);
                this.visor.combAlbums.setModel(new DefaultComboBoxModel(new String[] {"Album1","Album2","Album3","Album4","Album5","..."}));
                this.visor.listImatgesBiblioteca.setModel(model);
            }
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAfegirImatgeBiblioteca = new javax.swing.JButton();
        btnEliminarImatgeBiblioteca = new javax.swing.JButton();
        btnCrearAlbum = new javax.swing.JButton();
        btnEliminarAlbum = new javax.swing.JButton();
        combAlbums = new javax.swing.JComboBox();
        chkReprod = new javax.swing.JCheckBox();
        btnVisualitzarImatge = new javax.swing.JButton();
        btnVisualitzarBiblioteca = new javax.swing.JButton();
        btnVisualitzarAlbum = new javax.swing.JButton();
        btnVisualitzarImatgeAlbum = new javax.swing.JButton();
        btnEliminarImatgeAlbum = new javax.swing.JButton();
        etAlbum = new javax.swing.JLabel();
        etImatgeAlbum = new javax.swing.JLabel();
        etImatgeBiblioteca = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listImatgesBiblioteca = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listImatgesAlbum = new javax.swing.JList();
        etGPS = new javax.swing.JLabel();
        btnGuardarDades = new javax.swing.JButton();
        btnRecuperarDades = new javax.swing.JButton();
        btnAfegirImatgeAlbum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAfegirImatgeBiblioteca.setText("AFEGIR IMATGE");
        btnAfegirImatgeBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirImatgeBibliotecaActionPerformed(evt);
            }
        });

        btnEliminarImatgeBiblioteca.setText("ELIMINAR IMATGE(S)");
        btnEliminarImatgeBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarImatgeBibliotecaActionPerformed(evt);
            }
        });

        btnCrearAlbum.setText("CREAR ALBUM");
        btnCrearAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAlbumActionPerformed(evt);
            }
        });

        btnEliminarAlbum.setText("ELIMINAR ALBUM");
        btnEliminarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlbumActionPerformed(evt);
            }
        });

        combAlbums.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Album1","Album2","Album3","Album4","Album5","..."}));
        combAlbums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combAlbumsActionPerformed(evt);
            }
        });

        chkReprod.setText("Activa per reproduccio aleatoria");
        chkReprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReprodActionPerformed(evt);
            }
        });

        btnVisualitzarImatge.setText("VISUALITZAR IMATGE");
        btnVisualitzarImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarImatgeActionPerformed(evt);
            }
        });

        btnVisualitzarBiblioteca.setText("VISUALITZAR BIBLIOTECA");
        btnVisualitzarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarBibliotecaActionPerformed(evt);
            }
        });

        btnVisualitzarAlbum.setText("VISUALITZAR ALBUM");
        btnVisualitzarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarAlbumActionPerformed(evt);
            }
        });

        btnVisualitzarImatgeAlbum.setText("VISUALITZAR IMATGE");
        btnVisualitzarImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarImatgeAlbumActionPerformed(evt);
            }
        });

        btnEliminarImatgeAlbum.setText("ELIMINAR IMATGE(S)");
        btnEliminarImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarImatgeAlbumActionPerformed(evt);
            }
        });

        etAlbum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etAlbum.setText("Albums");

        etImatgeAlbum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etImatgeAlbum.setText("Imatge de l'album");

        etImatgeBiblioteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etImatgeBiblioteca.setText("Imatges de la biblioteca");

        listImatgesBiblioteca.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Imatge1","Imatge2","Imatge3","Imatge4","Imatge5","..."};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listImatgesBiblioteca);

        listImatgesAlbum.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Imatge1","Imatge2","Imatge3","Imatge4","Imatge5","..."};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listImatgesAlbum);

        etGPS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etGPS.setText("GPS:");

        btnGuardarDades.setText("GUARDAR DADES");
        btnGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDadesActionPerformed(evt);
            }
        });

        btnRecuperarDades.setText(" RECUPERAR DADES");
        btnRecuperarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarDadesActionPerformed(evt);
            }
        });

        btnAfegirImatgeAlbum.setText("IMATGE A L'ALBUM");
        btnAfegirImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirImatgeAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarImatgeBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisualitzarBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnVisualitzarImatge, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(chkReprod, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etImatgeBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAfegirImatgeBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminarAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combAlbums, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etGPS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAfegirImatgeAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etImatgeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEliminarImatgeAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualitzarImatgeAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualitzarAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecuperarDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfegirImatgeBiblioteca)
                    .addComponent(btnCrearAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etAlbum)
                        .addComponent(etImatgeAlbum))
                    .addComponent(etImatgeBiblioteca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combAlbums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etGPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAfegirImatgeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualitzarImatge)
                    .addComponent(btnEliminarAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualitzarBiblioteca)
                    .addComponent(btnEliminarImatgeAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarImatgeBiblioteca)
                    .addComponent(btnVisualitzarImatgeAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualitzarAlbum)
                    .addComponent(chkReprod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecuperarDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnEliminarImatgeBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImatgeBibliotecaActionPerformed
        for(int i: this.listImatgesBiblioteca.getSelectedIndices()){
            this.controlador.removeImage(this.controlador.getImage(i));
        }
        Actualitzador act=new Actualitzador(this);
        act.actualitzar();
        //Actualitzador act=new Actualitzador(new JButton[] {this.btnAfegirImatgeAlbum,this.btnEliminarAlbum,this.btnEliminarImatgeAlbum,this.btnEliminarImatgeBiblioteca,this.btnGuardarDades,this.btnVisualitzarAlbum,this.btnVisualitzarBiblioteca,this.btnVisualitzarImatge,this.btnVisualitzarImatgeAlbum},this.combAlbums,this.controlador,new JList[] {this.listImatgesBiblioteca,this.listImatgesAlbum});
        //act.actualitzar();
    }//GEN-LAST:event_btnEliminarImatgeBibliotecaActionPerformed

    private void btnEliminarImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImatgeAlbumActionPerformed
        for(int i: this.listImatgesAlbum.getSelectedIndices()){
            this.controlador.removeImage(this.controlador.getImage(i),this.combAlbums.getSelectedIndex());
        }
        Actualitzador act=new Actualitzador(this);
        act.actualitzar();
        //Actualitzador act=new Actualitzador(new JButton[] {this.btnAfegirImatgeAlbum,this.btnEliminarAlbum,this.btnEliminarImatgeAlbum,this.btnEliminarImatgeBiblioteca,this.btnGuardarDades,this.btnVisualitzarAlbum,this.btnVisualitzarBiblioteca,this.btnVisualitzarImatge,this.btnVisualitzarImatgeAlbum},this.combAlbums,this.controlador,new JList[] {this.listImatgesBiblioteca,this.listImatgesAlbum});
        //act.actualitzar();
    }//GEN-LAST:event_btnEliminarImatgeAlbumActionPerformed

    private void btnAfegirImatgeBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirImatgeBibliotecaActionPerformed
        FrmAfegirImatge afegImatge = new FrmAfegirImatge(this);    
    }//GEN-LAST:event_btnAfegirImatgeBibliotecaActionPerformed

    private void btnVisualitzarImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarImatgeActionPerformed
        try {
            this.controlador.showImg(this.controlador.getImage(this.listImatgesBiblioteca.getSelectedIndex()));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnVisualitzarImatgeActionPerformed

    private void btnVisualitzarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarBibliotecaActionPerformed
        try {
            this.controlador.play(this.controlador.getBibl());
        } catch (VisorException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnVisualitzarBibliotecaActionPerformed

    private void chkReprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReprodActionPerformed
        this.controlador.changeTipusReproduccio();
    }//GEN-LAST:event_chkReprodActionPerformed

    private void btnCrearAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlbumActionPerformed
        FrmCrearAlbum crearAlbum = new FrmCrearAlbum(this);
    }//GEN-LAST:event_btnCrearAlbumActionPerformed

    private void btnEliminarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlbumActionPerformed
        this.controlador.removeAlbum(this.combAlbums.getSelectedIndex());
        Actualitzador act=new Actualitzador(this);
        act.actualitzar();
        //Actualitzador act=new Actualitzador(new JButton[] {this.btnAfegirImatgeAlbum,this.btnEliminarAlbum,this.btnEliminarImatgeAlbum,this.btnEliminarImatgeBiblioteca,this.btnGuardarDades,this.btnVisualitzarAlbum,this.btnVisualitzarBiblioteca,this.btnVisualitzarImatge,this.btnVisualitzarImatgeAlbum},this.combAlbums,this.controlador,new JList[] {this.listImatgesBiblioteca,this.listImatgesAlbum});
        //act.actualitzar();
    }//GEN-LAST:event_btnEliminarAlbumActionPerformed

    private void btnVisualitzarImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarImatgeAlbumActionPerformed
        try {
            this.controlador.showImg(this.controlador.getImage(this.combAlbums.getSelectedIndex(), this.listImatgesAlbum.getSelectedIndex()));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnVisualitzarImatgeAlbumActionPerformed

    private void btnVisualitzarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarAlbumActionPerformed
        try {
            this.controlador.play(this.controlador.getAlb(this.combAlbums.getSelectedIndex()));
        } catch (VisorException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnVisualitzarAlbumActionPerformed

    private void btnAfegirImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirImatgeAlbumActionPerformed
        try {
            this.controlador.addImage(this.controlador.getImage(this.listImatgesBiblioteca.getSelectedIndex()), this.combAlbums.getSelectedIndex());
            Actualitzador act=new Actualitzador(this);
            act.actualitzar();
        } catch (ExcepcioImatgeRepetida ex) {
            JOptionPane.showMessageDialog(null, "Aquesta imatge ja existeix a la biblioteca");
        } catch (ExcepcioImatgeNoExisteix ex) {
            JOptionPane.showMessageDialog(null, "Aquesta imatge no existeix");
        }
    }//GEN-LAST:event_btnAfegirImatgeAlbumActionPerformed

    private void btnGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDadesActionPerformed
        FrmRutaDades frame=new FrmRutaDades(this,true);
    }//GEN-LAST:event_btnGuardarDadesActionPerformed

    private void btnRecuperarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarDadesActionPerformed
        FrmRutaDades frame=new FrmRutaDades(this,false);
    }//GEN-LAST:event_btnRecuperarDadesActionPerformed

    private void combAlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combAlbumsActionPerformed
        Actualitzador act=new Actualitzador(this);
        act.actualitzar();
    }//GEN-LAST:event_combAlbumsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisorUB4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirImatgeAlbum;
    private javax.swing.JButton btnAfegirImatgeBiblioteca;
    private javax.swing.JButton btnCrearAlbum;
    private javax.swing.JButton btnEliminarAlbum;
    private javax.swing.JButton btnEliminarImatgeAlbum;
    private javax.swing.JButton btnEliminarImatgeBiblioteca;
    private javax.swing.JButton btnGuardarDades;
    private javax.swing.JButton btnRecuperarDades;
    private javax.swing.JButton btnVisualitzarAlbum;
    private javax.swing.JButton btnVisualitzarBiblioteca;
    private javax.swing.JButton btnVisualitzarImatge;
    private javax.swing.JButton btnVisualitzarImatgeAlbum;
    private javax.swing.JCheckBox chkReprod;
    private javax.swing.JComboBox combAlbums;
    private javax.swing.JLabel etAlbum;
    private javax.swing.JLabel etGPS;
    private javax.swing.JLabel etImatgeAlbum;
    private javax.swing.JLabel etImatgeBiblioteca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listImatgesAlbum;
    private javax.swing.JList listImatgesBiblioteca;
    // End of variables declaration//GEN-END:variables
}
